version: "3.7"
services:
  gestion-geo:
    build:
      context: ./
      dockerfile: Dockerfile
    image: gestion-geo
    container_name: gestion-geo-app
    ports:
      - "5000:80"
    environment:
      - "REACT_APP_API_URL=http://127.0.0.1:8000/api"
